### ISSUE TITLE
Favicon and Page Title

### ISSUE THREAD

**Issue by maxtkc** [CRLSCSClub/CRLSTime#11]
The two lines below can be added to the <head> to make the page have a good looking tab. The title states what will be written and the link states what will be the icon to the left of that.
```
<title>CRLS Clock</title>
<link rel="shortcut icon" type="image/x-icon" href="falcon_high_res2.png" />

**Comment by dougmcg** [comment]
Max - let's use this revision to go through the process - you make the change and I'll merge it into the master... I need the practice.

**Comment by maxtkc** [comment]
Okay... Thanks!

**Comment by maxtkc** [comment]
Ready for merge!
For some reason, git used my dads email for the changes I made, but I think I figure out how to fix it.

**Comment by dougmcg** [comment]
So, do you now create a "pull request"?
