### ISSUE TITLE
Clock not loading on older browsers (like my iPhone 4s!) with refactored code

### ISSUE THREAD

**Issue by dougmcg** [CRLSCSClub/CRLSTime#26]
This is related to a recent update with code from Alon to clean up and separate code into different files. Possibly because var statements were replaced with let statements.

**Comment by psvenk** [comment]
Yes, `let` [has poor browser support](https://caniuse.com/#feat=let). I'm working on fixing this in #30 (while keeping Alon's other changes).

**Comment by psvenk** [comment]
I have now fixed this in #30. Marking as closed.

**Comment by psvenk** [comment]
Fixed in #39.
